-- 테이블 삭제
DROP TABLE IF EXISTS `CHAT`;
DROP TABLE IF EXISTS `REPLY`;
DROP TABLE IF EXISTS `DIARY_KEYWORD`;
DROP TABLE IF EXISTS `IMAGE`;
DROP TABLE IF EXISTS `DIARY`;
DROP TABLE IF EXISTS `CUSTOM`;
DROP TABLE IF EXISTS `AI_IMAGE`;
DROP TABLE IF EXISTS `AI`;
DROP TABLE IF EXISTS `KEYWORD`;
DROP TABLE IF EXISTS `MEMBER`;

-- 회원 테이블
CREATE TABLE `MEMBER` (
  `USER_ID`   VARCHAR(50)  NOT NULL,
  `EMAIL`     VARCHAR(50)  NOT NULL unique ,
  `NAME`      VARCHAR(20)  NOT NULL,
  `PASSWORD`  VARCHAR(200) NOT NULL,
  `ROLE`      VARCHAR(20)  NOT NULL,
  `ENABLED`   BOOLEAN      NOT NULL,
  PRIMARY KEY (`USER_ID`)
);

-- AI 캐릭터 테이블
CREATE TABLE `AI` (
  `AI_ID`     INT           NOT NULL AUTO_INCREMENT,
  `NAME`      VARCHAR(50)   NOT NULL,
  `MBTI`      VARCHAR(10)   NOT NULL,
  `INFO`      VARCHAR(500)  NOT NULL,
  `PROMPT`    VARCHAR(500)  NOT NULL,
  `IS_USE`    BOOLEAN       NOT NULL,
  PRIMARY KEY (`AI_ID`)
);

-- AI 캐릭터 이미지 테이블
CREATE TABLE `AI_IMAGE` (
    `AI_IMG_ID`     INT            NOT NULL AUTO_INCREMENT,
    `AI_ID`         INT            NOT NULL,
    `SAVE_PATH`     VARCHAR(500)   NOT NULL,
    `TYPE`          VARCHAR(36)    NOT NULL,
    `ORIGIN_NAME`   VARCHAR(255)   NOT NULL,
    `RENAMED_NAME`  VARCHAR(255)   NOT NULL,
    `IS_USE`        BOOLEAN        NOT NULL,
    PRIMARY KEY (`AI_IMG_ID`),
    FOREIGN KEY (`AI_ID`) REFERENCES `AI`(`AI_ID`)
);

-- 회원별 AI 커스텀
CREATE TABLE `CUSTOM` (
  `CUSTOM_ID` INT           NOT NULL AUTO_INCREMENT,
  `USER_ID`   VARCHAR(50)   NOT NULL,
  `AI_ID`     INT           NOT NULL DEFAULT 1,
  `IS_FORMAL` BOOLEAN       NOT NULL,
  `IS_LONG`   BOOLEAN       NOT NULL,
  PRIMARY KEY (`CUSTOM_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `MEMBER`(`USER_ID`),
  FOREIGN KEY (`AI_ID`) REFERENCES `AI`(`AI_ID`)
);

-- 일기 테이블
CREATE TABLE `DIARY` (
  `DIARY_ID`  INT           NOT NULL AUTO_INCREMENT,
  `USER_ID`   VARCHAR(50)   NOT NULL,
  `EMOTION`   VARCHAR(50)   NOT NULL,
  `CONTENT`   VARCHAR(1024) NOT NULL,
  `DATE`      DATE          NOT NULL,
  `CREATED_AT` TIMESTAMP    NOT NULL,
  `MODIFIED_AT` TIMESTAMP   NOT NULL,
  `IS_USE`    BOOLEAN       NOT NULL,
  PRIMARY KEY (`DIARY_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `MEMBER`(`USER_ID`)
);

-- 일기 사진 테이블
CREATE TABLE `IMAGE` (
  `IMG_ID`        INT            NOT NULL AUTO_INCREMENT,
  `DIARY_ID`      INT            NOT NULL,
  `SAVE_PATH`     VARCHAR(500)   NOT NULL,
  `TYPE`          VARCHAR(36)    NOT NULL,
  `ORIGIN_NAME`   VARCHAR(255)   NOT NULL,
  `RENAMED_NAME`  VARCHAR(255)   NOT NULL,
  `IS_USE`        BOOLEAN        NOT NULL,
  PRIMARY KEY (`IMG_ID`),
  FOREIGN KEY (`DIARY_ID`) REFERENCES `DIARY`(`DIARY_ID`)
);

-- 키워드 테이블
CREATE TABLE `KEYWORD` (
  `KEYWORD_ID`  INT           NOT NULL AUTO_INCREMENT,
  `NAME`        VARCHAR(50)   NOT NULL,
  `IS_USE`      BOOLEAN       NOT NULL,
  `TYPE`        VARCHAR(50)   NOT NULL,
  PRIMARY KEY (`KEYWORD_ID`)
);

-- 일기에 저장된 키워드
CREATE TABLE `DIARY_KEYWORD` (
  `DIARY_KEYWORD_ID` INT NOT NULL AUTO_INCREMENT,
  `DIARY_ID`         INT NOT NULL,
  `KEYWORD_ID`       INT NOT NULL,
  PRIMARY KEY (`DIARY_KEYWORD_ID`),
  FOREIGN KEY (`DIARY_ID`) REFERENCES `DIARY`(`DIARY_ID`),
  FOREIGN KEY (`KEYWORD_ID`) REFERENCES `KEYWORD`(`KEYWORD_ID`)
);

-- AI 답변 테이블
CREATE TABLE `REPLY` (
  `REPLY_ID`    INT           NOT NULL AUTO_INCREMENT,
  `DIARY_ID`    INT           NOT NULL,
  `AI_ID`       INT           NOT NULL,
  `CONTENT`     TEXT          NOT NULL,
  `CREATED_AT`  TIMESTAMP     NOT NULL,
  `MODIFIED_AT`  TIMESTAMP    NOT NULL,
  `IS_USE`      BOOLEAN       NOT NULL,
  PRIMARY KEY (`REPLY_ID`),
  FOREIGN KEY (`DIARY_ID`) REFERENCES `DIARY`(`DIARY_ID`),
  FOREIGN KEY (`AI_ID`) REFERENCES `AI`(`AI_ID`)
);

-- AI 채팅 테이블
CREATE TABLE `CHAT` (
  `CHAT_ID`     INT           NOT NULL AUTO_INCREMENT,
  `USER_ID`     VARCHAR(50)   NOT NULL,
  `REPLY_ID`    INT           NOT NULL,
  `CREATED_AT`  TIMESTAMP     NOT NULL,
  `MODIFIED_AT` TIMESTAMP     NOT NULL,
  `COUNT`       INT           NOT NULL,
  `IS_USE`      BOOLEAN       NOT NULL,
  PRIMARY KEY (`CHAT_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `MEMBER`(`USER_ID`),
  FOREIGN KEY (`REPLY_ID`) REFERENCES `REPLY`(`REPLY_ID`)
);
